const e=JSON.parse('{"key":"v-3fc1efc8","path":"/note/golang/open-source-books/the-way-to-go/13/13.4.html","title":"13.4 自定义包中的错误处理和 panicking","lang":"zh-CN","frontmatter":{},"headers":[],"git":{"updatedTime":1684038853000},"readingTime":{"minutes":0.24,"words":71},"filePathRelative":"note/golang/open-source-books/the-way-to-go/13/13.4.md","excerpt":"<h1> 13.4 自定义包中的错误处理和 panicking</h1>\\n<p>自定义包实现者应该遵守的最佳实践：</p>\\n<ol>\\n<li>\\n<p><em>在包内部，总是应该从 panic 中 recover</em>：不允许显式的超出包范围的 <code>panic()</code></p>\\n</li>\\n<li>\\n<p><em>向包的调用者返回错误值（而不是 panic）。</em></p>\\n</li>\\n</ol>"}');export{e as data};
